package Migration;

import static Migration.Instructions.*;

public class Program {
	static int code1[]={
			CONST,3,CONST,5,IMUL,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			WRITE,10,READ,10,PRINT
	};
	
	static int code2[]={
			CONST,3,CONST,5,IMUL,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			WRITE,10,READ,10,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			WRITE,10,READ,10,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			WRITE,10,READ,10,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			WRITE,10,READ,10,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,
			READ,5,READ,3,IADD,PRINT,	
			WRITE,10,READ,10,PRINT
	};

}
